### ISSUE TITLE
SegWit

### ISSUE THREAD

**Issue by chris41188** [bitpay/bitcore-lib#107]
Will this library be updated to use segwit? or is this something we must do manually?

**Comment by gabegattis** [comment]
We have a WIP pull request.
https://github.com/bitpay/bitcore-lib/pull/50

Not sure when we will finish it and get it merged into master though.

**Comment by chris41188** [comment]
Thanks! looking foward to it

**Comment by braydonf** [comment]
FYI https://github.com/bitpay/bitcore-lib/pull/50 is ready for testing against testnet with Bitcoin Core 0.13.0 and 0.13.1
