### ISSUE TITLE
Error importing bitcore-lib in react-native environment

### ISSUE THREAD

**Issue by mpolci** [bitpay/bitcore-lib#108]
I'm trying to use bitcore-lib in a react-native app. Getting an error at load time: 

> undefined is not a function (evaluating 'BufferUtil.isBuffer(argument)')

![screen2](https://cloud.githubusercontent.com/assets/6625359/19533947/28f63af4-9642-11e6-9f7b-3ffda3d9451e.png)

The problem is this code in the file lib/util/precondition.js:

``` javascript
if (type === 'Buffer') {
  var BufferUtil = require('./buffer');
  if (!BufferUtil.isBuffer(argument)) {
     throw new errors.InvalidArgumentType(argument, type, argumentName);
  }
} 
```

It seems that the `require('./buffer')` returns an empty object.

**Comment by bretth18** [comment]
I'm trying to figure out how to do the exact same thing, I look a suggestion mentioned in this thread:
https://github.com/mvayngrib/rn-nodeify/issues/15

and included my shim file, but it didn't help. Any ideas?

**Comment by mareksip** [comment]
This happens also when importing lib into Cordova environment.

**Comment by patrykwegrzyn** [comment]
I ended up having the same problem , any updates on this one ?

**Comment by garytofu** [comment]
Please see if modifying precondition.js as follow would work for you
```
        var buffer = require('buffer');
        if (!(buffer.Buffer.isBuffer(argument) || argument instanceof Uint8Array)){
          throw new errors.InvalidArgumentType(argument, type, argumentName);
        }
        // var BufferUtil = require('./buffer');
        // if (!BufferUtil.isBuffer(argument)) {
        //   throw new errors.InvalidArgumentType(argument, type, argumentName);
        // }
```

**Comment by patrykwegrzyn** [comment]
@garytofu thank you this worked for me

**Comment by jgarzik** [comment]
I'm seeing this same issue (right down to the same screenshot), with create-react-native-app + ReactNativify + bitcore-lib.
