### ISSUE TITLE
Is this library dead?

### ISSUE THREAD

**Issue by afk11** [bitpay/bitcore-lib#119]
Things are quiet around here, development-wise and addressing issues / old PR's. 

Is this library being maintained anymore? It seems to have been deprioritized

https://github.com/bitpay/bitcore-lib/pull/106#issuecomment-278042033 - trivial PR fixing a network incompatibility bug

https://github.com/bitpay/bitcore-lib/issues/73#issuecomment-278043236 - bigger PR, adds segwit, stalled since march.

Does this library have a future? Or should it be suggested people use something else as it's unmaintained?

**Comment by kleetus** [comment]
This library is still being actively maintained.

**Comment by afk11** [comment]
Then it would be great to see a commit once in a while, or completion of some of the outstanding work open a year or so.

**Comment by lichtamberg** [comment]
@kleetus Looks like its outdated?

**Comment by DaniGuardiola** [comment]
I'll take that as a yes.

**Comment by matiu** [comment]
it is not abandoned, it has segwit support already.
