### ISSUE TITLE
Increase maximum fee per KB threashold

### ISSUE THREAD

**Issue by visvirial** [bitpay/bitcore-lib#123]
As everyone complains, Bitcoin transaction fees required are constantly increasing (currently ~200sat/byte).

Bitcore checks the fee size when you create a transaction and abort if a fee is too high.
The threshold value is currently set to `FEE_SECURITY_MARGIN (=15) * 10 sat/byte * tx_size_in_bytes`.
https://github.com/bitpay/bitcore-lib/blob/master/lib/transaction/transaction.js#L223

Hench the threshold fee rate is effectively `150 sat/byte` which is too low for the current circumstance.

Please increase this threshold value.

---

You may set `disableLargeFees` option to disable the above safeguard mechanism as a workaround, but it is obviously not safe!

**Comment by gabegattis** [comment]
@visvirial I made a PR to bump up these values. I haven't fixed the tests yet, but you can see what I was thinking.

https://github.com/bitpay/bitcore-lib/pull/125

**Comment by visvirial** [comment]
@gabegattis Thank you.

**Comment by visvirial** [comment]
I was too lazy to follow the discussion, but it seems this issue has been resolved in #125 .
I will close this issue.

Thank you so much!
