### ISSUE TITLE
Is signing a transaction with bitcore-lib vulnerable to recovering private keys?

### ISSUE THREAD

**Issue by odyzxc** [bitpay/bitcore-lib#158]
Is signing a transaction with bitcore-lib vulnerable to recovering private keys while propagating more than one transaction using one input address? See http://www.nilsschneider.net/2013/01/28/recovering-bitcoin-private-keys.html fro more details.

**Comment by gabegattis** [comment]
We use deterministic k values when generating signatures, so we are protected against this issue.
