### ISSUE TITLE
bitcore-lib-cash: Point does not lie on the curve

### ISSUE THREAD

**Issue by Gamaroff** [bitpay/bitcore-lib#180]
When using the bitcore-lib-cash library the Error Point does not lie on the curve is thrown.

Using Typescript:

```
import BitcoreCash from 'bitcore-lib-cash';
let privateKey = new BitcoreCash.PrivateKey(); // throws Point does not lie on the curve 
```
Any pointers are much appreciated.

**Comment by arrix** [comment]
Are you using bitcore-lib and bitcore-lib-cash at the same time?

I can generate PrivateKeys and Addresses without any problem if I use bitcore-lib-cash alone. However, if both libs are imported, I get `Error: Point does not lie on the curve` when `pk.toPublicKey()` is called

```var bch = require('bitcore-lib-cash')
var bc = require('bitcore-lib')

(new bch.PrivateKey).toPublicKey()
(new bc.PrivateKey).toPublicKey()
```

**Comment by sail0778** [comment]
how to generate privatekey and adress can u tell me step by step and where
i can get sofware

regards

**Comment by Gamaroff** [comment]
Thanks @arrix.

The problem was because I was using Bitcore Mnemonic with the bitcore-lib-cash and they were conflicting. 

Bitcore Mnemonic uses bitcore-lib as a dependency.
Will there be a fix for that?

**Comment by arrix** [comment]
The conflict may be worked around by requiring the two libs in specific order.

```
// Error: Point does not lie on the curve
var bch = require('bitcore-lib-cash')
var bc = require('bitcore-lib')

(new bch.PrivateKey).toPublicKey()
(new bc.PrivateKey).toPublicKey()
```
Note that bitcore-lib-cash/lib/publickey.js called into bitcore-lib/lib/crypto/point.js.

> Error: Point does not lie on the curve
>     at Point.validate (/xxx/node_modules/bitcore-lib/lib/crypto/point.js:119:11)
>     at new PublicKey (/xxx/node_modules/bitcore-lib-cash/lib/publickey.js:53:14)
>     at Function.PublicKey.fromPrivateKey (/xxx/node_modules/bitcore-lib-cash/lib/publickey.js:221:10)
>     at PrivateKey.toPublicKey (/xxx/node_modules/bitcore-lib-cash/lib/privatekey.js:362:30)

If bitcore-lib is required before bitcore-lib-cash, it seems to work.
```
// seems to work
var bc = require('bitcore-lib')
var bch = require('bitcore-lib-cash')

(new bch.PrivateKey).toAddress()
(new bc.PrivateKey).toAddress()
```

**Comment by Gamaroff** [comment]
Cool thanks!

I'll give it a try.

**Comment by Gamaroff** [comment]
Thank you, @arrix 
I can confirm that it does indeed work with mnemonic now.

Thank you for the help!

**Comment by mohammadrafigh** [comment]
@Gamaroff be aware that this workaround may break some internal checks for point, public key, etc. the right solution has been provided in #238 also that PR should consider the same approach for bn.js IMO.
