### ISSUE TITLE
MultiSig Address not matched with bitcoinjs

### ISSUE THREAD

**Issue by thackerronak** [bitpay/bitcore-lib#222]
var bitcore = require('bitcore-lib');
var network = bitcore.Networks.testnet;
var adds1 = ['036ab181020a6d194b93f0468ef1dcec2725c9d62f985e5c44204eccdf7ea7f7bc',
'0212cfec75f672d79feaf9352ba3bb9ef12254db25fd3382672aff45a799d0a283',
'03908d80a38995dee0182072368155456f075e4ea23752f9be188d35aa3b154430' ];
var p2shAddress = new bitcore.Address.createMultisig(adds1, 2,network);
console.log(p2shAddress);
**<Address: 2MtGfpGS51zby2PusgGmM2o6PaaGy76dvxn, type: scripthash, network: testnet>**

var bitcoin = require('bitcoinjs-lib');
var network1 = bitcoin.networks.testnet;
var pubKeys = adds1.map(function (hex) { return Buffer.from(hex, 'hex') })
var redeemScript = bitcoin.script.multisig.output.encode(2, pubKeys)
var scriptPubKey = bitcoin.script.scriptHash.output.encode(bitcoin.crypto.hash160(redeemScript))
var address = bitcoin.address.fromOutputScript(scriptPubKey, network1);
console.log(address);
**2MsJoX4iTns4rfJ4xXs5VoLo6Ba153VdxPm**

Bitcore using the same algo. for Multisig ? or any way to get same address as bitcoinjs ?

**Comment by gabegattis** [comment]
I haven't looked into this much, but my first instinct would be to check if one is using compressed pubkeys and the other using uncompressed.

**Comment by matiu** [comment]
Iirc bitcore sorts the pubs keys. Try feeding bitcoinjs with the sorted
keys.

Alternatively i think there is a flag to noSort.

**Comment by fanatid** [comment]
`noSort` => `noSorting`, but it is not possible pass it to `Address.createMultisig`, so valid code:
```js
var p2shAddress = bitcore.Address.payingTo(bitcore.Script.buildMultisigOut(adds1, 2, { noSorting: true }), network)
```

**Comment by thackerronak** [comment]
@fanatid Thanks. It's working.
