### ISSUE TITLE
how can i use two from to sendtransaction?

### ISSUE THREAD

**Issue by RXien** [bitpay/bitcore-lib#246]
i would like to set two vin like this 

var utxo = {
  "txId" : "115e8f72f39fad874cfab0deed11a80f24f967a84079fb56ddf53ea02e308986",
  "outputIndex" : 0,
  "address" : address,
  "script" : "76a91447862fe165e6121af80d5dde1ecb478ed170565b88ac",
  "satoshis" : 50000
};

var tx = new litecore.Transaction()
tx.from(utxo)
tx.from(utxo)
tx.to(address, 15000)
tx.sign(privateKey);
console.log(tx.toString())

**Comment by wooolfgang** [comment]
Try passing the utxos as an array 
` tx.from(utxos) `

**Comment by gabegattis** [comment]
This is not litecore, but bitcore works by passing in an array of utxos.
