### ISSUE TITLE
Use for Bitcoin Gold (BTG)

### ISSUE THREAD

**Issue by cenyG** [bitpay/bitcore-lib#254]
Hi, I'm trying to send transaction using this library for BTG but have error
`16: mandatory-script-verify-flag-failed (Signature hash type missing or not understood)`
I'm creating transaction using bitcore.Transaction() and then sendRawTransaction.
Anybody can make advice for me how can I do this?

**Comment by matiu** [comment]
BTG is not supported by bitcore-lib.  Signatures are different.
