### ISSUE TITLE
zcash-hackworks/bitcore-lib-zcash can't sign transaction

### ISSUE THREAD

**Issue by ztlovemst11** [bitpay/bitcore-lib#264]
I use zcash's test address to sign the transaction with the transaction method, returning an error.
Obviously, only btc addresses are available.
[ https://github.com/zcash-hackworks/bitcore-lib-zcash](url)

**Comment by ztlovemst11** [comment]
How to use the zcash-hackworks/bitcore-lib-zcash library in the right way?

**Comment by fanatid** [comment]
Why not submit this issue in github.com/zcash-hackworks/bitcore-lib-zcash ?

**Comment by ztlovemst11** [comment]
@fanatid [https://github.com/zcash-hackworks/bitcore-lib-zcash](url)The issue on this page is not available

**Comment by ztlovemst11** [comment]
So I have to come to the source of his fork to ask questions.

**Comment by matiu** [comment]
@ztlovemst11 this repo does not support zcash, sorry.
