### ISSUE TITLE
hd wallet transaction fail while submitting the hash .

### ISSUE THREAD

**Issue by alishaagupta** [bitpay/bitcore-lib#273]
error code: -26 error message: 16: mandatory-script-verify-flag-failed (Operation not valid with the current stack size)

**Comment by alishaagupta** [comment]
Do one need to use private keys of all the addresses or the ones whose utxos are being used?

**Comment by matiu** [comment]
we can't help with only that.

please submit a snipped with  the code and a way to reproduce the error.

**Comment by alishaagupta** [comment]
https://gist.github.com/alishaagupta/2f39fe11e618ad897d4fbdb2f17f2aa2

@matiu
