### ISSUE TITLE
`isReplaceByFee` method to check sequence number

### ISSUE THREAD

**Issue by braydonf** [bitpay/bitcore-lib#28]
And other related methods and support.

Related: https://github.com/bitcoin/bitcoin/pull/6871

**Comment by petertodd** [comment]
You probably want to call this IsOptInRBF - with full-RBF all transactions "are" replace-by-fee.

**Comment by braydonf** [comment]
Forgot to mention that this would be a method on Transaction, so would only be needed with opt-in (and no need to distinguish from full-RBF):

```js
transaction.isReplaceByFee(); // checks the sequence number
```
Though it may be better to just have an `isFinal` method, and it RBF can be checked conveniently with:
```js
var isRBF = !transaction.isFinal();
```

**Comment by petertodd** [comment]
Please don't confuse finality with RBF - the concept of a transaction being "final" has well-defined consensus-critical semantics.

**Comment by braydonf** [comment]
Indeed, that could be confusing. Perhaps this shorthand:

```js
transaction.isMaxSequence();
```

**Comment by petertodd** [comment]
Opt-in RBF is maxint - 2, maxint - 1 is not max sequence, yet is also not opt-in RBF.
