### ISSUE TITLE
Idea: `transaction.normalizedHash` for transaction malleability 

### ISSUE THREAD

**Issue by braydonf** [bitpay/bitcore-lib#29]
As mentioned in https://github.com/bitcoin/bips/commit/916142e742b4256686c26b15a0bf943aea3f5ef9 a normalized transaction id could help with transaction malleability.

For example, an additional method on Transaction could exist:
```js
if (tx1.normalizedHash() === tx2.normalizedHash()) {
  // the transaction effect "from -> to" is equivalent
}
```

The hash could be calculated (similar to sighash: https://github.com/bitpay/bitcore-lib/blob/master/lib/transaction/sighash.js):

1. Sort transaction using https://github.com/bitcoin/bips/blob/master/bip-0069.mediawiki ?
2. Remove all input scripts
3. Clear the sequenceNumber and nLockTime?
4. Serialize transaction and then hash it

It could then be possible to search Insight via a normalized hash, with an additional index added.

Related: https://github.com/bitcoin/bips/pull/244

**Comment by unusualbob** [comment]
Just as reference, when I was messing around with this a while back this was the function I came up with. Keep in mind this hasn't been super vetted. I did monitor the blockcypher double spend websocket to get lots of double spend txs to compare, but I don't have tests for each case.

```js
function generateNormalizedId(transaction) {
  var rawTxData = "";

  rawTxData += transaction.version;
  rawTxData += transaction.nLockTime || 0;

  for(var i = 0; i < transaction.inputs.length; i++) {
    var input = transaction.inputs[i];

    rawTxData += input.outputIndex;
    rawTxData += input.prevTxId.toString('hex');

    if (input.script) {
      var inputAddressInfo = input.script.toAddress();
      if (inputAddressInfo) {
        rawTxData += inputAddressInfo.type;
        rawTxData += inputAddressInfo.hashBuffer.toString('hex');
      }
    }
    if (input.sequenceNumber) {
      rawTxData += input.sequenceNumber;
    }
  }

  for (i = 0; i < transaction.outputs.length; i++) {
    var output = transaction.outputs[i];
    rawTxData += output.satoshis;

    if (output.script) {
      var outputAddressInfo = output.script.toAddress();
      if (outputAddressInfo) {
        rawTxData += outputAddressInfo.type;
        rawTxData += outputAddressInfo.hashBuffer.toString('hex');
      }
    }
  }

  return bitcore.crypto.Hash.sha256ripemd160(new Buffer(rawTxData, 'utf8'));
```

**Comment by gabegattis** [comment]
Now that segregated witness is a thing, this is probably not worth working on. I think we should close this. @braydonf ?

**Comment by braydonf** [comment]
Good point
