### ISSUE TITLE
Issues creating browser bundle

### ISSUE THREAD

**Issue by langri-sha** [bitpay/bitcore-lib#34]
It appears that `crypto-browserify` no longer supports `ripemd160`, as it was renamed to `rmd160` some versions ago. See [here](https://github.com/crypto-browserify/crypto-browserify/blob/master/index.js#L7).

This affects Browserify and Webpack builds (since Webpack uses `crypto-browserify` as a `crypto` replacement for browser bundles).

**Comment by langri-sha** [comment]
This is a quick and dirty solution.

```
import crypto, {createHash as sourceCreateHash} from 'crypto';

crypto.createHash = function createHash(alg) {
    if (alg === 'ripemd160') {
        alg = 'rmd160';
    }

    return sourceCreateHash(alg);
}
```

**Comment by braydonf** [comment]
Both 'ripemd160' and 'rmd160' should be the same: https://github.com/crypto-browserify/crypto-browserify/issues/135

**Comment by langri-sha** [comment]
It seems that the additional aliases never made it to master. This is what I get using the latest `crypto-browserify`:

```
npm install -g crypto-browserify@latest
node -e "require('crypto-browserify').createHash('rmd160')"
node -e "require('crypto-browserify').createHash('ripemed160')"
/node_modules/crypto-browserify/node_modules/sha.js/index.js:3
  if(!Alg) throw new Error(alg + ' is not supported (we accept pull requests)')
           ^

Error: ripemed160 is not supported (we accept pull requests)
    at module.exports (/node_modules/crypto-browserify/node_modules/sha.js/index.js:3:18)
    at Object.module.exports [as createHash] (/node_modules/crypto-browserify/create-hash.js:29:10)
    at [eval]:1:30
    at Object.exports.runInThisContext (vm.js:54:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:398:26)
    at node.js:592:27
    at nextTickCallbackWith0Args (node.js:433:9)
    at process._tickCallback (node.js:362:13)
```

**Comment by Levino** [comment]
So what is the proper solution for this?

**Comment by gkucmierz** [comment]
@langri-sha your solution is not working for me.
Can you explain how to solve the problem?

**Comment by gkucmierz** [comment]
I found dirty solution.
I moved bitcore-lib to angular assets, included it old fashion way in index.html
and I used it in my code like that:
const {PrivateKey} = window['require']('bitcore-lib');

Very dirty solution, but it is something wrong with this package.

**Comment by vidul-nikolaev-petrov** [comment]
A quick patch that works for me (React and Electron):

```javascript
(function() {
    const orgCreateHash = crypto.createHash;

    crypto.createHash = algo => orgCreateHash(algo === 'ripemd160' ? 'rmd160' : algo);
})();
```

**Comment by DalderupMaurice** [comment]
For people who are still having this issue.
Update: webpack, the thing causing the error is: node-libs-browser within webpack.

This package pulled in an old version of createHash within crypto-browserify.
