### ISSUE TITLE
Modularised browser build

### ISSUE THREAD

**Issue by JustinDrake** [bitpay/bitcore-lib#35]
I'm looking to build a light version of bitcore-lib with *just* Bitcoin URIs, and the necessary dependencies. The full library (600kB+) is too large for my browser use case.

How can I do a modularised browser build?

**Comment by fanatid** [comment]
```js
require('bitcore-lib/lib/uri')
```

**Comment by JustinDrake** [comment]
@fanatid: I'm looking for a browser build which produces a file with a small footprint.

**Comment by fanatid** [comment]
I understand, but if you will use `require('bitcore-lib/lib/uri')` instead `require('bitcore-lib')` you got 570kB instead 600kB after compressed. But it's too small change :(
I checked source code size and got next results: 320kb for uncompressed and 65kb for compressed (`find lib -type f -exec cat {} + | gzip -c | wc -c`), so it looks like you can't get small footprint only for URI :(

**Comment by JustinDrake** [comment]
320kb is pretty good! How did you get that?

**Comment by braydonf** [comment]
Most of the modules are connected in some fashion, so requiring one file will require most of the library. A gzipped minified browser build should be around 176K. Also most of the library has already been modularized that reduced the file size dramatically:
- https://github.com/bitpay/bitcore-payment-protocol
- https://github.com/bitpay/bitcore-p2p
- https://github.com/bitpay/bitcore-mnemonic
- https://github.com/bitpay/bitcore-channel
- https://github.com/bitpay/bitcore-message
- https://github.com/bitpay/bitcore-ecies

**Comment by fanatid** [comment]
@JustinDrake 320kb is a size only of all bitcore-lib files without dependencies
