### ISSUE TITLE
Implement segregated witness

### ISSUE THREAD

**Issue by afk11** [bitpay/bitcore-lib#42]
AFAICT, bitcore-lib is the only JS library with a reimplementation of the bitcoins interpreter - I'd like to get the ability to verify/sign segwit transactions in there ASAP. 

Verification is OK - add extra structures to transactions, implement the v0 transaction digest algorithm, and add the changes to verifyScript so we can verify the extra scripts. 

Signing is a bit tricky, I eventually rewrote my signer to follow Bitcoin Core.. It should solve any of pay-to-pubkey, pay-to-pubkey-hash, and multisig, whether it's a standard output script, P2SH, or P2SH|Witness. WitnessV0Keyhash is accepted via P2SH or as an output script. 

I can probably contribute towards verification, which mainly only affects the interpreter and transactions.. But it'd be nice to know if someone's working on signing, as it touches transactions as well.

**Comment by braydonf** [comment]
@afk11  Just got transaction signing working for `Transaction.sign` for [nested witness p2sh](https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki#Witness_program_nested_in_BIP16_P2SH) at branch https://github.com/braydonf/bitcore-lib/tree/segwit in https://github.com/braydonf/bitcore-lib/commit/6e800e37096d13685f0058162dc6ddb5a34dd10f and tested against https://github.com/sipa/bitcoin/tree/segwit.

Updating the interpretor for the new consensus rules still needs work and contributions welcome. I've put together a detailed list of items here: https://github.com/bitpay/bitcore-lib/issues/49

**Comment by afk11** [comment]
Nice, that's certainly the hardest case :) Pity there isn't support for plain witness transactions in Core yet - only re-implementations provide easy access to those at the moment.. I'll take another look at my shot at verification in a bit!
