### ISSUE TITLE
Segwit/segnet development support

### ISSUE THREAD

**Issue by braydonf** [bitpay/bitcore-lib#49]
Here is a rough breakdown of tasks needed to bring segwit support to bitcore libraries:

**Bitcore Library:**
- **Address**
  - New address type for pay-to-witness-public-key-hash and pay-to-witness-script-hash ([BIP0142](https://github.com/bitcoin/bips/blob/master/bip-0142.mediawiki)) DEFERRED
  - Expand associated address methods to use the new formats to build the corresponding scripts DEFERRED
- **Transaction**
  -  **New transaction serialization format**, expand `toBuffer`/`fromBuffer` for bitcore-lib to include additional support for segwit serialization format. This is mostly identical to existing implementation with an additional flag that indicates segwit tx, and a new field for `scriptWitness` on the input ([BIP0144](https://github.com/bitcoin/bips/blob/master/bip-0144.mediawiki)) IMPLEMENTED
  -  **New transaction hash** that does not include witness, and one that does include the witness ([BIP0144](https://github.com/bitcoin/bips/blob/master/bip-0144.mediawiki))  IMPLEMENTED
  - Support signing inputs with the new witness programs for pay-to-witness-public-key-hash and pay-to-witness-script-hash ([BIP0141](https://github.com/bitcoin/bips/blob/master/bip-0144.mediawiki))
  - **Support signing inputs and making transactions with traditional P2SH with segwit** ([BIP0141](https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki)). IMPLEMENTED
- **Network**
  - Add segnet network alongside and similar to regtest network options IMPLEMENTED
- **Script**
  - Add script evaluation for witness data  ([BIP0141](https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki)) IMPLEMENTED (needs more tests)
- **Block**
  - New block size rule that discounts signatures/witnesses ([BIP0141](https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki))
  - Support getting the witness merkle commitment for a block ([BIP0141](https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki))

**Bitcore P2P Library**
- New handshake p2p message for "havewitness" sent after "verack" ([BIP0144](https://github.com/bitcoin/bips/blob/master/bip-0144.mediawiki))
- New inventory types for `MSG_WITNESS_TX` and `MSG_WITNESS_BLOCK` for getdata messages ([BIP0144](https://github.com/bitcoin/bips/blob/master/bip-0144.mediawiki))

**Comment by braydonf** [comment]
Work in progress branch: https://github.com/braydonf/bitcore-lib/tree/segwit

**Comment by braydonf** [comment]
Implemented at branch https://github.com/braydonf/bitcore-lib/tree/segwit in https://github.com/braydonf/bitcore-lib/commit/6e800e37096d13685f0058162dc6ddb5a34dd10f:
- Witness transaction serialization format and hash
- Witness sighash
- Nested p2sh multisig witness transaction signing
- Segnet network

**Comment by braydonf** [comment]
Signed tx: https://segnet.smartbit.com.au/tx/cac2029d9269c79c4923df11abd7e261f04d8be1f39376c5081abe06596cd205 from test https://github.com/braydonf/bitcore-lib/blob/6e800e37096d13685f0058162dc6ddb5a34dd10f/test/transaction/transaction.js#L1236

**Comment by dabura667** [comment]
Suggestion:

Change the default toAddress() for single sig newly generated keys to be P2SH( WPKH ).

So looking at this example:
http://n.bitcoin.ninja/checktx?txid=8139979112e894a14f8370438a471d23984061ff83a9eba0bc7a34433327ec21

```
pubkeyHex = "038262a6c6cec93c2d3ecd6c6072efea86d02ff8e3328bbd0242b20af3425990ac"
      hash160Hex = "1d7cd6c75c2e86f4cbf98eaed221b30bd9a0b928" (for "1" address)
redeemScript = "00141d7cd6c75c2e86f4cbf98eaed221b30bd9a0b928"
               (segwit 0x00 + serialized push of hash160)
```

Then run that redeemscript through P2SH as default.

This way people will by default be creating addresses to send to segwit p2sh, encouraging usage.

Also, checking balance for keys (is there a function for that?) should check this p2sh by default for segwit.

**Comment by lichtamberg** [comment]
Any progress on this?

**Comment by braydonf** [comment]
@lichtamberg See https://github.com/bitpay/bitcore-lib/pull/50

**Comment by lichtamberg** [comment]
@braydonf thanks.. But it's not really clear what this means :D Is there any ETA when segwit will be fully implemented?

**Comment by afk11** [comment]
It's been pending work so you can sign all the other scripts in P2WSH + P2SH|P2WSH. I really looks like this project has been deprioritized. Try running bitcore (with bitcoind) on testnet!
