### ISSUE TITLE
Outside require references are being searched within bitcore-lib

### ISSUE THREAD

**Issue by mareksip** [bitpay/bitcore-lib#56]
Hi, thanks for this library.

I'm using bitcore-lib in my Cordova app and found weird issue when using require for bitcoinjs-lib. 

Once I include bitcore to the project following with [bitcoinjs](https://github.com/bitcoinjs/bitcoinjs-lib)

    <script src="lib/bitcore-lib/bitcore-lib.js"></script>
    <script src="lib/bitcoinjs-lib/bitcoinjs.js"></script>

and use require for other scripts :

    var bitcoin = require("bitcoinjs-lib");
    var bigi = require("bigi");
    var buffer = require('buffer');

I receive error:

> Error: Cannot find module 'bitcoinjs-lib' at s (bitcore-lib.js:1)

Isn't there something wrong with bitcore-lib require functions that other require outside bitcorelib is searching within the bitcore-lib?

**Comment by mareksip** [comment]
Any updates, please?

**Comment by braydonf** [comment]
This may be an issue with how your building bitcoinjs, `require` isn't exported as the standalone flag may be used, and therefore it's using require as defined by bitcore.

**Comment by braydonf** [comment]
I was able to reproduce the issue, but it's not an issue here.
