### ISSUE TITLE
Safari crashes when running tests with karma

### ISSUE THREAD

**Issue by eordano** [bitpay/bitcore-lib#78]
I've been seeing some weird behavior in Safari for a web application that signs transactions.  The error was pointed out because invalid signatures were being received by the server.

I was wondering if that was caused by `bitcore-lib`, so I tried adding `karma-safari-launcher` to the list of launchers in `bitcore-build`. This causes my Safari to crash randomly after running between 100 and 1500 tests (out of the ~3000 of `bitcore`); so I couldn't verify that all tests pass on this browser.

Update: all tests run correctly

![screen shot 2016-06-14 at 11 37 08 am](https://cloud.githubusercontent.com/assets/42750/16046902/661e310c-3224-11e6-9c08-e3ce6e414eae.png)

**Comment by eordano** [comment]
It looks like all tests pass correctly, it is just a karma issue when trying to run the tests:

![screen shot 2016-06-14 at 12 04 51 pm](https://cloud.githubusercontent.com/assets/42750/16047899/4cc39d06-3228-11e6-9d76-bca600ae3e4e.png)

**Comment by braydonf** [comment]
@eordano Indeed looks like an issue with karma, just ran the tests using `test/index.html` file with `python -m SimpleHTTPServer` and had 3027 tests passing with no failures with Safari 8.0.5

**Comment by braydonf** [comment]
Closing as karma only runs Firefox, and tests are all passing in Safari.
